pcm.multi {
    type route
    slave.pcm {
        type multi
        slaves.a.pcm "front"
        slaves.a.channels 2
        slaves.b.pcm "loopin"
        slaves.b.channels 2
        slaves.c.pcm "hdmi"
        slaves.c.channels 8
        bindings.0.slave c
        bindings.0.channel 0
        bindings.1.slave c
        bindings.1.channel 1
        bindings.2.slave c
        bindings.2.channel 2
        bindings.3.slave c
        bindings.3.channel 3
        bindings.4.slave c
        bindings.4.channel 4
        bindings.5.slave c
        bindings.5.channel 5
        bindings.6.slave c
        bindings.6.channel 6
        bindings.7.slave c
        bindings.7.channel 7
        bindings.8.slave b
        bindings.8.channel 0
        bindings.9.slave b
        bindings.9.channel 1
        bindings.10.slave a
        bindings.10.channel 0
        bindings.11.slave a
        bindings.11.channel 1
    }
    ttable.0.0 0.7
    ttable.1.1 0.1
    ttable.2.2 0.45
    ttable.3.3 0.4
    ttable.4.4 0.65
    ttable.5.5 0.3
    ttable.6.6 0.65
    ttable.7.7 0.7
    ttable.0.8 0.33333
    ttable.1.9 0.33333
    ttable.2.8 0.33333
    ttable.3.9 0.33333
    ttable.4.8 0.33333
    ttable.5.9 0.33333
    ttable.6.8 0.33333
    ttable.7.9 0.33333
    ttable.0.10 0.33333
    ttable.1.11 0.33333
    ttable.2.10 0.33333
    ttable.3.11 0.33333
    ttable.4.10 0.33333
    ttable.5.11 0.33333
    ttable.6.10 0.33333
    ttable.7.11 0.33333
}

pcm.randomatones {
    type plug
    slave.pcm "multi"
}

pcm.loopin {
    type plug
    slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
    type plug
    slave.pcm "hw:Loopback,1,0"
}

