pcm.multi {
    type route;
    slave.pcm {
        type multi
        slaves.a.pcm "hdmi"
        slaves.b.pcm "loopin"
        slaves.a.channels 8
        slaves.b.channels 2
        bindings.0.slave a
        bindings.0.channel 0
        bindings.1.slave a
        bindings.1.channel 1
        bindings.2.slave a
        bindings.2.channel 2
        bindings.3.slave a
        bindings.3.channel 3
        bindings.4.slave a
        bindings.4.channel 4
        bindings.5.slave a
        bindings.5.channel 5
        bindings.6.slave a
        bindings.6.channel 6
        bindings.7.slave a
        bindings.7.channel 7
        bindings.8.slave b
        bindings.8.channel 0
        bindings.9.slave b
        bindings.9.channel 1
    }

    ttable.0.0 1
    ttable.1.1 1
    ttable.2.2 1
    ttable.3.3 1
    ttable.4.4 1
    ttable.5.5 1
    ttable.6.6 1
    ttable.7.7 1
    ttable.0.8 0.25
    ttable.1.8 0.25
    ttable.2.8 0.25
    ttable.3.8 0.25
    ttable.4.9 0.25
    ttable.5.9 0.25
    ttable.6.9 0.25
    ttable.7.9 0.25
}

pcm.randomatones {
	type plug
	slave.pcm "multi"
} 

pcm.loopin {
	type plug
	slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
	type plug
	slave.pcm "hw:Loopback,1,0"
}
