pcm.splitter {
    type route;
    slave.pcm {
        type multi
        slaves.a.pcm "surround51"
        slaves.b.pcm "loopin"
        slaves.a.channels 6
        slaves.b.channels 2
        bindings.0.slave a
        bindings.0.channel 0
        bindings.1.slave a
        bindings.1.channel 1
        bindings.2.slave a
        bindings.2.channel 2
        bindings.3.slave a
        bindings.3.channel 3
        bindings.4.slave a
        bindings.4.channel 4
        bindings.5.slave a
        bindings.5.channel 5
        bindings.6.slave b
        bindings.6.channel 0
        bindings.7.slave b
        bindings.7.channel 1
    }

    ttable.0.0 1
    ttable.1.1 1
    ttable.2.2 1
    ttable.3.3 1
    ttable.4.4 1
    ttable.5.5 1
    ttable.0.6 0.33
    ttable.1.6 0.33
    ttable.2.6 0.33
    ttable.3.7 0.33
    ttable.4.7 0.33
    ttable.5.7 0.33
}

pcm_slave.usb48k1 {
    pcm "hw:2,0"
    rate 48000
}


pcm.composite {
    type multi
    slaves.a.pcm {
        type plug
        slave "usb48k1"
    }
    slaves.a.channels 2
    slaves.b.pcm {
        type plug
        slave.pcm "hw:1,0"
    }
    slaves.b.channels 2
    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave a
    bindings.1.channel 1
    bindings.2.slave b
    bindings.2.channel 0
    bindings.3.slave b
    bindings.3.channel 1
}

pcm.fourway {
    type plug
    slave.pcm "composite"
}

pcm.randomatones {
    type plug
    slave.pcm "splitter"
} 

pcm.loopin {
    type plug
    slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
    type plug
    slave.pcm "hw:Loopback,1,0"
}
