pcm.splitter {
    type route;
    slave.pcm {
        type multi
        slaves.a.pcm "surround51"
        slaves.b.pcm "loopin"
        slaves.a.channels 6
        slaves.b.channels 2
        bindings.0.slave a
        bindings.0.channel 0
        bindings.1.slave a
        bindings.1.channel 1
        bindings.2.slave a
        bindings.2.channel 2
        bindings.3.slave a
        bindings.3.channel 3
        bindings.4.slave a
        bindings.4.channel 4
        bindings.5.slave a
        bindings.5.channel 5
        bindings.6.slave b
        bindings.6.channel 0
        bindings.7.slave b
        bindings.7.channel 1
    }

    ttable.0.0 1
    ttable.1.1 1
    ttable.2.2 1
    ttable.3.3 1
    ttable.4.4 1
    ttable.5.5 1
    ttable.0.6 0.33
    ttable.1.6 0.33
    ttable.2.6 0.33
    ttable.3.7 0.33
    ttable.4.7 0.33
    ttable.5.7 0.33
}

pcm.randomatones {
	type plug
	slave.pcm "splitter"
} 

pcm.loopin {
	type plug
	slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
	type plug
	slave.pcm "hw:Loopback,1,0"
}
