pcm.multi {
    type route
    slave.pcm {
        type multi
        slaves.a.pcm "hw:0,0"
        slaves.a.channels 2
        slaves.b.pcm "loopin"
        slaves.b.channels 2
        bindings.0.slave b
        bindings.0.channel 0
        bindings.1.slave b
        bindings.1.channel 1
        bindings.2.slave a
        bindings.2.channel 0
        bindings.3.slave a
        bindings.3.channel 1
    }
    ttable.0.0 0.33333
    ttable.1.1 0.33333
    ttable.2.0 0.33333
    ttable.3.1 0.33333
    ttable.4.0 0.33333
    ttable.5.1 0.33333
    ttable.0.2 0.33333
    ttable.1.3 0.33333
    ttable.2.2 0.33333
    ttable.3.3 0.33333
    ttable.4.2 0.33333
    ttable.5.3 0.33333
}

pcm.randomatones {
    type plug
    slave.pcm "multi"
}

pcm.loopin {
    type plug
    slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
    type plug
    slave.pcm "hw:Loopback,1,0"
}

