
pcm_slave.onboard {
    pcm "hw:1,0"
    rate 44100
}

pcm.onb {
    type plug
    slave "onboard"
}

pcm_slave.usb_ms {
    pcm "hw:2,0"
    rate 44100
}

pcm.usb1 {
    type plug
    slave "usb_ms"
}

pcm_slave.usb_3 {
    pcm "hw:3,0"
    rate 44100
}

pcm.usb2 {
    type plug
    slave "usb_3"
}

pcm.composite {
    type multi
    slaves.a.pcm "onb"
    slaves.a.channels 1
    slaves.b.pcm "usb1"
    slaves.b.channels 2
    slaves.c.pcm "usb2"
    slaves.c.channels 2
    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave b
    bindings.1.channel 0 
    bindings.2.slave b
    bindings.2.channel 1
    bindings.3.slave c
    bindings.3.channel 0 
    bindings.4.slave c
    bindings.4.channel 1
}


pcm.multiroute {
    type route
    slave.pcm "composite"
    slave.channels 5
    ttable.0.0 1
    ttable.1.1 1
    ttable.2.2 1
    ttable.3.3 1
    ttable.4.4 1
}


pcm.randomatones {
    type plug
    slave.pcm "composite"
}
