pcm_slave.usb48k_1 {
    pcm "hw:2,0"
    rate 48000
}

pcm_slave.onboard {
    pcm "hw:1,0"
    rate 48000
}

pcm.composite {
    type multi
    slaves.a.pcm {
        type plug
        slave "usb48k_1"
    }
    slaves.a.channels 2
    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave a
    bindings.1.channel 1 
}


pcm.randomatones {
    type plug
    slave.pcm "hw:1,0"
}
