#!/bin/bash
set -e
startAt="$1"
stopAt="$2"
args=($@)
avoidDays=(${args[@]:2})
today=$(date +%u)

as_mins() {
    hs=${1%:*}
    ms=${1#*:}
    hh=$((10#$hs))
    mm=$((10#$ms))
    echo $(((60 * hh) + mm))
}

plural() {
    if [ $1 -eq 1 ]; then echo ''; else echo 's'; fi
}

as_time() {
    t=$1
    hh=$((t / 60))
    mm=$((t % 60))

    ts=()
    if [ $hh -gt 0 ]
    then
        hp=$(plural $hh)
        ts+=(${hh}hr$hp)
    fi
    mp=$(plural $mm)
    ts+=(${mm}min$mp)
    echo "${ts[*]}"
}

as_weekday() {
    local d=$1
    local days=(Mon Tues Wednes Thurs Fri Satur Sun)
    echo "${days[$((d - 1))]}day"
}

time_diff() {
    from=$(as_mins "$1")
    to=$(as_mins "$2")
    d=$((to-from))
    echo $(as_time $d)
}


runs_on() {
    if [[ ${avoidDays[@]} =~ $1 ]]
    then
        echo 0
    else
        echo 1
    fi
}


next_run_day_after() {
    d=$((($1 % 7) + 1))
    r=$(runs_on $d)
    if [ $r = 0 ]
    then
        echo $(next_run_day_after $d)
    else
        echo $d
    fi
}


next_run_day() {
    n=$(next_run_day_after $today)
    echo $(as_weekday $n)
}


instruct_player() {
    tmux send-keys -t 1 $1
    exit
}


for ad in ${avoidDays[@]}
do
    if [ $today = $ad ]
    then
        echo "does not run today ($(as_weekday $today))"
        echo "resumes $(next_run_day) at $startAt"
        exit
    fi
done

timeNow=$(date +%H:%M)
if [ ! "$timeNow" \< "$stopAt" ]
then
    echo "stopped at $stopAt ($(time_diff $stopAt $timeNow) ago)"
    echo "resumes at $startAt $(next_run_day)"
    instruct_player 'p'
fi

if [ "$timeNow" \< "$startAt" ]
then
    echo "resuming at $startAt in $(time_diff $timeNow $startAt)"
    instruct_player 'p'
else
    echo "running at $timeNow"
    echo "pausing at $stopAt in $(time_diff $timeNow $stopAt)"
    instruct_player 'r'
fi
